/* =========================================================
   REPERTORIO — MARO MUSIC
   -----------------------------------------------------------
   Para AGREGAR una canción: copia una línea dentro del género
   correspondiente y cambia "title" y "artist".
   Para AGREGAR un género nuevo: copia un bloque completo
   { genre: "...", songs: [...] } y ajústalo.
   Esta es una lista de EJEMPLO — reemplázala por tu repertorio real.
   ========================================================= */

const REPERTOIRE = [
  {
    genre: "Salsa Romántica",
    songs: [
      { title: "Flor Palida", artist: "Marc Anthony" },
      { title: "Hasta ayer", artist: "Marc Anthony" },
      { title: "No me conoces", artist: "Marc Anthony" },
      { title: "Y hubo Alguien", artist: "Marc Anthony" },
      { title: "Vivir lo nuestro", artist: "Marc Anthony" },
      { title: "Porque te amo", artist: "Nino Segarra" },
      { title: "La persona ideal", artist: "Adolecentes" },
      { title: "Virgen", artist: "Adolecentes" },
      { title: "Derroche", artist: "Aldo Matta" },
      { title: "Para tenerte siempre", artist: "Aldo Matta" },
      { title: "Sin condicion alguna", artist: "Charlie Aponte" },
      { title: "Pensando en ti", artist: "Cheche Mendoza" },
      { title: "Vamos a darnos tiempo", artist: "Conjunto Chaney" },
      { title: "Hasta el sol de hoy", artist: "Edgar Joel" },
      { title: "Hechizo de luna", artist: "Edgar Joel" },
      { title: "Amor cuanto te amo", artist: "Grupo Galé" },
      { title: "Dime que no paso", artist: "Grupo Galé" },
      { title: "Donde se quedo", artist: "Grupo Galé" },
      { title: "Me basta", artist: "Grupo Galé" },
      { title: "Olvidalo", artist: "Grupo Galé" },
      { title: "Perdoname", artist: "Grupo Galé" },
      { title: "Ven a medellin", artist: "Grupo Galé" },
      { title: "Algo que se quede", artist: "Grupo Niche" },
      { title: "Busca por dentro", artist: "Grupo Niche" },
      { title: "Cali aji", artist: "Grupo Niche" },
      { title: "Cali pachanguero", artist: "Grupo Niche" },
      { title: "La magia de tus besos", artist: "Grupo Niche" },
      { title: "Sin sentimientos", artist: "Grupo Niche" },
      { title: "Me canse", artist: "Harveys" },
      { title: "Gracias amor", artist: "Matecaña" },
      { title: "A medellin", artist: "Nelson Hernandez" },
      { title: "Lloraras", artist: "Oscar de Leon" },
      { title: "Tu ausencia", artist: "Pedro Arroyo" },
      { title: "Lagrimas", artist: "Roberto Blades" },
      { title: "Artista famoso", artist: "Roberto Blades" },
      { title: "Amor y control", artist: "Ruben Blades" },
      { title: "No lo beses", artist: "Salsa libre" },
      { title: "Fantasma", artist: "Son de Cali" },
      { title: "Te amo", artist: "Son de Cali" },
      { title: "Un amante como yo", artist: "Suprema corte" },
      { title: "Ella se hizo deseo", artist: "Tito Rojas" },
      { title: "Pequeñas cosas", artist: "Willie gonzales" },
      { title: "No podras escapar de m", artist: "Willie gonzales" },
      { title: "Como se queda", artist: "Willie gonzales" },
      { title: "A prueba de fuego", artist: "Willy Garcia" },
      { title: "Ave de paso", artist: "Willy Garcia" },
      { title: "Lo que te sobre", artist: "Willy Garcia" },
      { title: "Todo por amor", artist: "Willy Garcia" },
      { title: "Y entonces", artist: "Willy Garcia" },
      { title: "Corazon de acero", artist: "Yiyo Sarante" },
      { title: "manos de tijera", artist: "Yiyo Sarante" },
    ],
  },
  {
    genre: "Rock en Español",
    songs: [
      { title: "Al otro lado del silencio", artist: "Angeles del infierno" },
      { title: "Pensando en ti", artist: "Angeles del infierno" },
      { title: "Flaca", artist: "Andres Calamaro" },
      { title: "Dios como puedo", artist: "Bailo y cospiro" },
      { title: "No dejes que", artist: "Caifanes" },
      { title: "Afuera", artist: "Caifanes" },
      { title: "Eterna soledad", artist: "Enanitos verdes" },
      { title: "Mi primer dia sin ti", artist: "Enanitos verdes" },
      { title: "Tu carcel", artist: "Enanitos verdes" },
      { title: "Muralla verde", artist: "Enanitos verdes" },
      { title: "Lamento Boliviano", artist: "Enanitos verdes" },
      { title: "Igual que ayer", artist: "Enanitos verdes" },
      { title: "Luz de dia", artist: "Enanitos verdes" },
      { title: "En algun lugar", artist: "Duncan dhu" },
      { title: "La chispa adecuada", artist: "Heroes del silencio" },
      { title: "El lado oscuro", artist: "Jarabe de palo" },
      { title: "Lenguaje de mi piel", artist: "Kraken" },
      { title: "Vestido de cristal", artist: "Kraken" },
      { title: "Mentira", artist: "La Ley" },
      { title: "Lobo hombre en paris", artist: "La union" },
      { title: "No mas", artist: "Los de adentro" },
      { title: "Una canción", artist: "Los de adentro" },
      { title: "Nubes negras", artist: "Los de adentro" },
      { title: "Mujer amante", artist: "Rata Blanca" },
      { title: "Entre canibales", artist: "Soda estereo" },
      { title: "Un nuevo amor", artist: "Tranzas" },
      { title: "Una sonrisa al atardecer", artist: "Akash" },
      { title: "Segundo plato", artist: "Vos Veis" },
      { title: "Aunque sea poco", artist: "Vos Veis" },
    ],
  },
  {
    genre: "Baladas Románticas",
    songs: [
      { title: "Llorar", artist: "Joan Sebastian" },
      { title: "Secreto de amor", artist: "Joan Sebastian" },
      { title: "Rumores", artist: "Joan Sebastian" },
      { title: "Me retaste a quererte", artist: "Guillermo Davila" },
      { title: "Melina", artist: "Camilo Sexto" },
      { title: "Mientras tu me sigas necesitando", artist: "Camilo Sexto" },
      { title: "Quieres ser mi amante", artist: "Camilo Sexto" },
      { title: "Tarde o temprano", artist: "Camilo Sexto" },
      { title: "Memorias", artist: "Rudy Marquez" },
      { title: "Pasado Pasado", artist: "Jose Jose" },
      { title: "Nohelia", artist: "Nino Bravo" },
      { title: "Ven junto a mi", artist: "Claudio Bermudez" },
      { title: "Otro ocupa mi lugar", artist: "Miguel Gallardo" },
    ],
  },
  {
    genre: "Tropical",
    songs: [
      { title: "Amor a primera vista", artist: "Combo de las Estrellas" },
      { title: "Con el alma enamorada", artist: "Combo de las Estrellas" },
      { title: "Me voy para medellin", artist: "Combo de las Estrellas" },
      { title: "Me voy para medellin Sinfonico", artist: "Combo de las Estrellas" },
      { title: "Esposa mia", artist: "Combo de las Estrellas" },
      { title: "El amor que te doy", artist: "Combo de las Estrellas" },
      { title: "Triste navidad", artist: "Jairo Patermina" },
      { title: "En aquellos años", artist: "Jorge Grajales" },
      { title: "Es tarde ya", artist: "Jorge Grajales" },
      { title: "La ingrata", artist: "Jorge Grajales" },
      { title: "Quiero ser feliz", artist: "Jorge Grajales" },
      { title: "Si supieras", artist: "Jorge Grajales" },
      { title: "Chipi Chipi", artist: "Los Melodicos" },
      { title: "El ausente", artist: "Pastor Lopez" },
      { title: "El hijo ausente", artist: "Pastor Lopez" },
      { title: "Las caleñas", artist: "Pastor Lopez" },
      { title: "Mujercita buena", artist: "Pastor Lopez" },
      { title: "Tormentos", artist: "Rodolfo Aicardi" },
      { title: "Quien eres tu", artist: "Tropicombo" },
      { title: "Distancia", artist: "Tropicombo" },
      { title: "El amor que te doy", artist: "Tropicombo" },
      { title: "Encanto", artist: "Tropicombo" },
      { title: "Hasta el final", artist: "Tropicombo" },
      { title: "Juntos para siempre", artist: "Tropicombo" },
    ],
  },
  {
    genre: "Música Popular y Banda",
    songs: [
      { title: "Aquí abajo", artist: "Cristian Nodal" },
      { title: "No te contaron mal", artist: "Cristian Nodal" },
      { title: "Probablemente", artist: "Cristian Nodal" },
      { title: "Ya no somos ni seremos", artist: "Cristian Nodal" },
      { title: "El amor no tiene edad", artist: "El Andariego" },
      { title: "Dulce pecado", artist: "Jessi Uribe" },
      { title: "Matemos las ganas", artist: "Jessi Uribe" },
      { title: "OK", artist: "Jessi Uribe" },
      { title: "Repitela", artist: "Jessi Uribe" },
      { title: "Basta con licor", artist: "Luis Alberto Posada" },
      { title: "EL precio de tu error", artist: "Luis Alberto Posada" },
      { title: "Me tomas y me dejas", artist: "Luis Alberto Posada" },
      { title: "Si supieras", artist: "Luisito Muñoz" },
      { title: "Prohibido", artist: "Paola Jara con Franko" },
      { title: "Tenias razón", artist: "Yeison Jimenez" },
      { title: "Ya no mi amor", artist: "Yeison Jimenez" },
      { title: "Mlp", artist: "Yeison Jimenez" },
      { title: "Maldita traga", artist: "Yeison Jimenez" },
      { title: "Porque la envidia", artist: "Yeison Jimenez" },
      { title: "Que dia es hoy", artist: "Yeison Jimenez" },
      { title: "Destino Final", artist: "Yeison Jimenez" },
      { title: "Hasta la madre", artist: "Yeison Jimenez" },
      { title: "Ni tengo ni necesito", artist: "Yeison Jimenez" },
      { title: "Aventurero", artist: "Yeison Jimenez" },
      { title: "Costumbres", artist: "Yeison Jimenez" },
      { title: "Sabras", artist: "Herencia timbiqui y Paola Jara" },
      { title: "Mi ultimo deseo", artist: "Los recoditos" },
      { title: "El beneficio de la duda", artist: "Grupo Firme" },
      { title: "Si te pudiera mentir", artist: "Calibre 50" },
    ],
  },
  {
    genre: "POP",
    songs: [
      { title: "Antes", artist: "Obie Bermudez" },
      { title: "Amor Gitano", artist: "Andres Cepeda" },
      { title: "El carpintero", artist: "Andres Cepeda" },
      { title: "Me voy", artist: "Andres Cepeda" },
      { title: "Se morir", artist: "Andres Cepeda" },
      { title: "Guerras Perdidas", artist: "Bacilos" },
      { title: "Tabaco y chanel", artist: "Bacilos" },
      { title: "Alejate de mi", artist: "Camila" },
      { title: "Coleccionista de canciones", artist: "Camila" },
      { title: "Mientes", artist: "Camila" },
      { title: "Todo cambio", artist: "Camila" },
      { title: "Dejame", artist: "Juan Fernando Velasco" },
      { title: "Dicen", artist: "Juan Fernando Velasco" },
      { title: "Para que no me olvides", artist: "Juan Fernando Velasco" },
      { title: "De rodillas", artist: "Lucas Arnau" },
      { title: "Tienes", artist: "Lucas Arnau" },
      { title: "Creo en ti", artist: "Reik" },
      { title: "Yo quisiera", artist: "Reik" },
      { title: "Desde lejos", artist: "Santiago Cruz" },
      { title: "Lo que me quedo", artist: "Santiago Cruz" },
      { title: "No nos digamos mentiras", artist: "Santiago Cruz" },
      { title: "Y si te quedas que", artist: "Santiago Cruz" },
      { title: "Mientes tambien", artist: "Sin Bandera" },
      { title: "Te vi venir", artist: "Sin Bandera" },
      { title: "Suelta mi mano", artist: "Sin Bandera" },
      { title: "Entra en mi vida", artist: "Sin Bandera" },
      { title: "Que lloro", artist: "Sin Bandera" },
      { title: "Kilometros", artist: "Sin Bandera" },
      { title: "A donde va el amor", artist: "Ricardo Montaner" },
      { title: "Te quise olvidar", artist: "Mdo" },
      { title: "Debajo de la almohada", artist: "Jose Miguel Diez" },
      { title: "Colgando en tus manos", artist: "Carlos Baute y Martha Sanchez" },
      { title: "Llorar y llorar", artist: "Jessi Joy y Mario Domm" },
      { title: "Nada valgo sin tu amor", artist: "Juanes" },
      { title: "Es por ti", artist: "Juanes" },
      { title: "Nada de nada", artist: "Marco di Mauro" },
      { title: "Penelope", artist: "Diego Torres" },
      { title: "Mi historia entre tus dedos", artist: "Gianluca Grignani" },
    ],
  },
  {
    genre: "Vallenatos",
    songs: [
      { title: "Ayer y hoy", artist: "Jean Carlos Centeno" },
      { title: "Despues del adios", artist: "Heber Vargas" },
      { title: "No he podido ser feliz", artist: "Heber Vargas" },
      { title: "Hasta que regreses", artist: "Propuesta vallenata" },
      { title: "Como te atreves", artist: "Daniel Calderon" },
      { title: "Que le dire al corazon", artist: "Daniel Calderon" },
      { title: "Me parte el corazon", artist: "Daniel Calderon" },
    ],
  },
  {
    genre: "Merengue",
    songs: [
      { title: "Entregame tu amor", artist: "Bananas" },
      { title: "Mas que amiga", artist: "Bananas" },
      { title: "Te amo mas", artist: "Bananas" },
      { title: "Tu eres ajena", artist: "Eddy Herrera" },
      { title: "Nuestra canción", artist: "Elvis Crespo" },
      { title: "Noches de fantasia", artist: "Joseph Fonseca" },
      { title: "Te compro tu novia", artist: "Ramon Orlando" },
      { title: "Si alguna dia la vez", artist: "Sergio Vargas" },
    ],
  },
];
